### ISSUE TITLE
function Logger._send_report() not yet implemented

### ISSUE THREAD

**Issue by kyleellefsen** [flika-org/flika#13]

**Comment by kyleellefsen** [comment]
I've hidden the "Send Bug Report" button, but I'll leave this issue open as a TODO.

**Comment by BrettJSettle** [comment]
I can set up a python anywhere server as a REST api that flika sends error
reports to. And a login to view the reports that people have submitted.

On Mar 27, 2017 2:19 PM, "Kyle Ellefsen" <notifications@github.com> wrote:

I've hidden the "Send Bug Report" button, but I'll leave this issue open as
a TODO.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/flika-org/flika/issues/13#issuecomment-289582593>, or mute
the thread

**Comment by kyleellefsen** [comment]
This works.
